version: "0.1"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis_db
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis_db:
    container_name: redis
    image: sameersbn/redis:4.0.9-1
    ports:
      - "6379:6379"
    restart: always